# Copyright 2020 Huy Le Nguyen (@usimarit)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

speech_config:
  sample_rate: 16000
  frame_ms: 25
  stride_ms: 10
  num_feature_bins: 80
  feature_type: log_mel_spectrogram

decoder_config:
  type: wordpiece

  blank_index: 0
  unknown_token: "[PAD]"
  unknown_index: 0

  beam_width: 0
  norm_score: True
  lm_config: null

  vocabulary: ./vocabularies/librispeech/wordpiece/train_1000_50.tokens
  vocab_size: 1000
  max_token_length: 50
  max_unique_chars: 1000
  reserved_tokens:
    - "[PAD]"
  normalization_form: NFKC
  num_iterations: 4

  corpus_files:
    - E:/MLDL/Datasets/ASR/LibriSpeech/train-clean-100/transcripts.tsv
    - E:/MLDL/Datasets/ASR/LibriSpeech/train-clean-360/transcripts.tsv
    - E:/MLDL/Datasets/ASR/LibriSpeech/train-other-500/transcripts.tsv

model_config:
  name: conformer
  encoder_subsampling:
    type: vgg
    filters:
      - 64
      - 128
    kernel_size: 3
    pool_size: 2
    strides: 2
    padding: same
    activation: relu
  encoder_positional_encoding: sinusoid
  encoder_dmodel: 144
  encoder_num_blocks: 16
  encoder_head_size: 36 # == dmodel // num_heads
  encoder_num_heads: 4
  encoder_mha_type: relmha
  encoder_kernel_size: 32
  encoder_fc_factor: 0.5
  encoder_dropout: 0.1
  encoder_padding: same
  prediction_label_encode_mode: embedding
  prediction_embed_dim: 320
  prediction_num_rnns: 1
  prediction_rnn_units: 320
  prediction_rnn_type: lstm
  prediction_rnn_implementation: 2
  prediction_rnn_unroll: False # False to use with CUDA or dynamic length, True to use with TPU and static length
  prediction_layer_norm: True
  prediction_projection_units: 0
  joint_dim: 320
  prejoint_encoder_linear: True
  prejoint_prediction_linear: True
  postjoint_linear: False
  joint_activation: tanh
  joint_mode: add

learning_config:
  train_dataset_config:
    enabled: True
    use_tf: True
    augmentation_config:
      feature_augment:
        gauss_noise:
          prob: 0.1
          stddev: 0.075
        time_masking:
          prob: 0.5
          num_masks: 10
          mask_factor: 100
          p_upperbound: 0.05
        freq_masking:
          prob: 0.5
          num_masks: 1
          mask_factor: 27
    data_paths:
      - E:/MLDL/Datasets/ASR/LibriSpeech/train-clean-100/transcripts.tsv
    tfrecords_dir: E:/MLDL/Datasets/ASR/LibriSpeech/tfrecords/wordpiece-1000/
    shuffle: True
    cache: True
    buffer_size: 100
    drop_remainder: True
    stage: train
    metadata: ./vocabularies/librispeech/wordpiece/train_1000_50.metadata.json

  eval_dataset_config:
    enabled: False
    use_tf: True
    data_paths:
      - E:/MLDL/Datasets/ASR/LibriSpeech/dev-clean/transcripts.tsv
    tfrecords_dir: null
    shuffle: False
    cache: True
    buffer_size: 100
    drop_remainder: True
    stage: eval
    metadata: ./vocabularies/librispeech/wordpiece/train_1000_50.metadata.json

  test_dataset_config:
    use_tf: True
    data_paths:
      - E:/MLDL/Datasets/ASR/LibriSpeech/test-clean/transcripts.tsv
    tfrecords_dir: null
    shuffle: False
    cache: True
    buffer_size: 100
    drop_remainder: True
    stage: test

  optimizer_config:
    beta_1: 0.9
    beta_2: 0.98
    epsilon: 1e-9

  learning_rate_config:
    warmup_steps: 10000
    max_lr_numerator: 0.05

  running_config:
    batch_size: 2
    num_epochs: 100
    checkpoint:
      filepath: D:/Models/local/conformer/checkpoints/{epoch:02d}.h5
      save_best_only: False
      save_weights_only: True
      save_freq: epoch
    states_dir: D:/Models/local/conformer/states
    tensorboard:
      log_dir: D:/Models/local/conformer/tensorboard
      histogram_freq: 1
      write_graph: True
      write_images: True
      update_freq: epoch
      profile_batch: 2
